package porta;

import porta.interfaces.IFactory;
import porta.interfaces.IFilesHandler;
import props.Settings;

public class Main {
	
	IFilesHandler handler; 
	IFactory factory;
	
	public Main(IFilesHandler handler, IFactory factory) {
		this.handler = handler;
		this.factory = factory;
	}
	
	public void main(String action) throws Exception {
				
		if (action == null) {
			System.out.println("Must specify an action");
			return;
		}
		
		String basefilename = Settings.get().getPath("dir.porta", "file.basename");
		
		String detailedname = handler.createFilename(Settings.get().getString("file.basename"));
		String detailedfilename = handler.createFilename(basefilename);
		
		String specificname = detailedname + "." + Settings.get().getString("file.specificname");
		String specificfilename = detailedfilename + "." + Settings.get().getString("file.specificname");
		
		String graphfile = basefilename + ".in";
		String ieqfile = detailedfilename + ".ieq";
		String poifile = detailedfilename + ".poi";
		String traffile = detailedfilename + ".poi.ieq";
		String modelfile = detailedfilename + ".model";
		String specificmodelfile = specificfilename + ".model";
		String specificportafile = specificfilename + ".ieq";
		
		Boolean preprocess = Settings.get().getBoolean("writer.preprocess");

		if (action.equalsIgnoreCase("--ieq")) {
			System.out.println("Writing ieq file from input graph");
			new WriteIeq(factory).write(graphfile, ieqfile, preprocess);
		} else if (action.equalsIgnoreCase("--process")) {
			System.out.println("Processing ieq file");
			new ProcessIeq(factory).process(graphfile, traffile, modelfile);
		} else if (action.equalsIgnoreCase("--name")) {
			System.out.println(detailedname);
		} else if (action.equalsIgnoreCase("--sname")) {
			System.out.println(specificname);
		} else if (action.equalsIgnoreCase("--poi")) {
			System.out.println("Writing poi file from input graph");
			new WritePoi(factory).write(graphfile, poifile, preprocess);
		} else if (action.equalsIgnoreCase("--translate")) {
			System.out.println("Translating from specific model file to porta file");
			new TranslateModel(factory).translate(specificmodelfile, specificportafile);
		} else if (action.equalsIgnoreCase("--readdim")) {
			System.out.println("Reading dimension lines from poi files generated by dim\n");
			ReadDim.read(specificportafile);
		} else {
			System.err.println("Invalid action specified " + action);
		}
	}

	
	
}
