/* Generated By:JavaCC: Do not edit this line. PortaParserConstants.java */
package porta.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PortaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int EQUALS = 7;
  /** RegularExpression Id. */
  int LEQ = 8;
  /** RegularExpression Id. */
  int GEQ = 9;
  /** RegularExpression Id. */
  int ASSIGN = 10;
  /** RegularExpression Id. */
  int LPAREN = 11;
  /** RegularExpression Id. */
  int RPAREN = 12;
  /** RegularExpression Id. */
  int DIM = 13;
  /** RegularExpression Id. */
  int LOWERB = 14;
  /** RegularExpression Id. */
  int UPPERB = 15;
  /** RegularExpression Id. */
  int VALID = 16;
  /** RegularExpression Id. */
  int INEQS = 17;
  /** RegularExpression Id. */
  int END = 18;
  /** RegularExpression Id. */
  int VARNAME = 19;
  /** RegularExpression Id. */
  int NUMBER = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"DIM\"",
    "\"LOWER_BOUNDS\"",
    "\"UPPER_BOUNDS\"",
    "\"VALID\"",
    "\"INEQUALITIES_SECTION\"",
    "\"END\"",
    "<VARNAME>",
    "<NUMBER>",
  };

}
